Some docu changes
gardener/landscaper-service pull request #8
Opened 2022-01-13 14:22 UTC by achimweigel

**What this PR does / why we need it**:

Some docu changes.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user
NONE
```

2022-01-13 15:13 UTC, robertgraeff approved these changes

2022-01-13 16:57 UTC, reshnm requested changes

2022-01-13 16:57 UTC, reshnm commented on docs/gettingstarted/create-landscaper-deployment.md
> +k -n laas-user get instances.landscaper-service.gardener.cloud test-8qh5w
```suggestion
kubectl -n laas-user get instances.landscaper-service.gardener.cloud test-8qh5w
```

2022-01-13 16:58 UTC, reshnm commented on docs/gettingstarted/create-landscaper-deployment.md
> +k -n laas-user get instances.landscaper-service.gardener.cloud test-8qh5w
This was some copy paste error by me. Should be `kubectl` instead of just `k` which probably only works on my machine :-)

2022-01-14 08:01 UTC, reshnm approved these changes

2022-01-14 08:02 UTC, merged