Export OIDC kubeconfig
gardener/landscaper-service pull request #97
Opened 2023-02-14 11:24 UTC by enrico-kaack-comp

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2023-02-14 12:46 UTC, achimweigel requested changes

2023-02-14 12:46 UTC, achimweigel commented on .landscaper/landscaper-instance/blueprint/rbac/export-execution.yaml
> +            - '--oidc-issuer-url= {{ .imports.shootConfig.kubernetes.kubeAPIServer.oidcConfig.issuerURL }}'
is here a blank after '='?

2023-02-14 12:52 UTC, enrico-kaack-comp commented on .landscaper/landscaper-instance/blueprint/rbac/export-execution.yaml
> +            - '--oidc-issuer-url= {{ .imports.shootConfig.kubernetes.kubeAPIServer.oidcConfig.issuerURL }}'
good catch, thanks

2023-02-15 10:00 UTC, reshnm approved these changes
/lgtm

2023-02-17 08:39 UTC, robertgraeff approved these changes

2023-02-20 04:46 UTC, achimweigel requested changes
I'm not sure but it looks as if the integration tests are always failing

2023-02-20 10:02 UTC, achimweigel approved these changes
/lgtm

2023-02-20 10:03 UTC, merged